# Generated by Django 3.1.2 on 2020-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animaldisease',
        ),
    ]
