# Generated by Django 3.1.2 on 2020-11-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0002_delete_animaldisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animaldisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
