# Generated by Django 3.1.2 on 2020-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0003_animaldisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldisease',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
