# Generated by Django 3.1.2 on 2020-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0004_auto_20201105_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldisease',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
